name: Unit Tests (PR)

on:
  pull_request:
    branches: ['canary', 'master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - run: make test
